---
title: "Himalayan Data Tidy Tuesday"
format: html
editor: visual
---

```{r include=FALSE}
library(readr)
library(tidyverse)
```

```{r message=FALSE}
exped_tidy <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-01-21/exped_tidy.csv')
peaks_tidy <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-01-21/peaks_tidy.csv')
```

```{r}
joined_data <- exped_tidy %>%
  left_join(peaks_tidy)
```

```{r}
joined_data_cleaned <- joined_data %>%
  mutate(success_any = SUCCESS1 | SUCCESS2 | SUCCESS3 | SUCCESS4) %>%
  select(EXPID, PEAKID, YEAR, SEASON_FACTOR, success_any, HEIGHTM) %>%
  mutate(SEASON_FACTOR = factor(SEASON_FACTOR, levels = c("Winter", "Spring", "Summer", "Autumn")))
```


```{r}
joined_data_cleaned %>%
  ggplot(aes(x=SEASON_FACTOR,fill=success_any))+
    geom_bar()+
    theme_classic()+
    labs(title="Seasonality of Himalayan Mountaineering Expeditions", x="Season", y="number of expeditions, 2020-2024", fill="success, any route")+
    scale_fill_manual(labels = c("none", "success"), values=c("#CC79A7", "#009E73"))
```

